config/routes.rb
EMenu::Application.routes.draw do

  devise_for :users 

  devise_scope :user do
    get 'users', :to => 'users#show', :as => :user_root # Rails 3
  end

  resources :menu_items
  resources :users, only: [:show]

  root to: 'static_pages#home' 

  match '/about', to: "static_pages#about"
  match '/contact', to: "static_pages#contact"
  match '/help', to: "static_pages#help"

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/item_type.rb
class ItemType
  include Mongoid::Document
  field :name, localize: true
  has_many :menu_items
end

app/models/menu_item.rb
class MenuItem
  include Mongoid::Document
  field :name, :type => String
  field :description, :type => String
  field :price, :type => BigDecimal
  belongs_to :item_type
end

app/models/user.rb
class User
  include Mongoid::Document
  
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :image

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :name, :type => String
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  field :image, :type => String

  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :encrypted_password
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String

  # Mount the uploader
  mount_uploader :image, ImageUploader
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def set_locale
    logger.debug "* Accept-Language: #{request.env['HTTP_ACCEPT_LANGUAGE']}"
    I18n.locale = extract_locale_from_accept_language_header || I18n.default_locale
    logger.debug "* Locale set to '#{I18n.locale}'"
  end
  
  private
  def extract_locale_from_accept_language_header
    request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  # GET /menu_items
  # GET /menu_items.json
  def index
    @menu_items = MenuItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @menu_items }
    end
  end

  # GET /menu_items/1
  # GET /menu_items/1.json
  def show
    @menu_item = MenuItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @menu_item }
    end
  end

  # GET /menu_items/new
  # GET /menu_items/new.json
  def new
    @menu_item = MenuItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @menu_item }
    end
  end

  # GET /menu_items/1/edit
  def edit
    @menu_item = MenuItem.find(params[:id])
  end

  # POST /menu_items
  # POST /menu_items.json
  def create
    @menu_item = MenuItem.new(params[:menu_item])

    respond_to do |format|
      if @menu_item.save
        format.html { redirect_to @menu_item, notice: 'Menu item was successfully created.' }
        format.json { render json: @menu_item, status: :created, location: @menu_item }
      else
        format.html { render action: "new" }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /menu_items/1
  # PUT /menu_items/1.json
  def update
    @menu_item = MenuItem.find(params[:id])

    respond_to do |format|
      if @menu_item.update_attributes(params[:menu_item])
        format.html { redirect_to @menu_item, notice: 'Menu item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_items/1
  # DELETE /menu_items/1.json
  def destroy
    @menu_item = MenuItem.find(params[:id])
    @menu_item.destroy

    respond_to do |format|
      format.html { redirect_to menu_items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :authenticate_user!

	def show
		@user = User.find(current_user.id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
  def type_name( item_type )
    item_type.nil? ? "---" : item_type.name
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
%footer.footer
	%small
		eMenu by 
		%a{href: "#"} PerrIT
	%nav
		%ul
			%li= link_to t('help'), help_path
			%li= link_to t('about_us'), about_path
			%li= link_to t('contact'), contact_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
	.navbar-inner
		.container
			= link_to "eMenu", root_path, class: 'brand'
			%nav
				%ul.nav.pull-right
					- if user_signed_in?
						%li= link_to t('home'), user_path
						%li#fat-menu.dropdown 
							%a{href: '#', class: 'dropdown-toggle', data: { toggle: 'dropdown'}}
								%i.icon-user.icon-white 
								= current_user.name
								%b.caret
							%ul.dropdown-menu
								%li= link_to t('menus'), menu_items_path
								%li= link_to t('edit_account'), edit_user_registration_path, id: 'edit_account'
								%li.divider
								%li= link_to(t('sign_out'), destroy_user_session_path, :method => 'delete', id: 'sign_out')
					- else
						%li= link_to t('home'), root_path
						%li= link_to(t('sign_up'), new_user_registration_path, id: 'sign_up')
						%li= link_to(t('sign_in'), new_user_session_path, id: 'sign_in')

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
	%div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
		%a.close{"data-dismiss" => "alert"} &#215;
		= content_tag :div, msg, id: "flash_#{name}" if msg.is_a?(String)

app/views/layouts/application.html.haml
!!!
%html
  %head
    /%meta{:charset => "utf-8"}
    /%meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    /%meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "eMenu"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    / Le styles
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      = render 'layouts/messages'
      = yield
      = render 'layouts/footer'

app/views/menu_items/_form.html.haml
= form_for @menu_item do |f|
  = render 'shared/error_messages', :object => f.object

  = f.label t('menu_item.name') 
  = f.text_field :name, :class => "span6"
  
  = f.label t('menu_item.description') 
  = f.text_area :description, :class => "span6", :rows => 10

  = f.label t('menu_item.type')
  = collection_select(:menu_item, :item_type_id, ItemType.all, :id, :name, {:include_blank => t(:select_blank)}, :class => "span6")

  = f.label t('menu_item.price')
  = f.text_field :price, :class => "span6"
  
  = f.submit t('menu_item.save'), class: "btn btn-large btn-success"

app/views/menu_items/edit.html.haml
%h1 Editing menu_item

.row
	%div{class: "span6 offset3" }
		= render 'form'

.form-actions
	= link_to t(:show), @menu_item
	|
	= link_to t(:back), menu_items_path

app/views/menu_items/index.html.haml
%h1 Listing menu_items

%table{:class => "table table-striped"}
  %tr
    %th= t('menu_item.name')
    %th= t('menu_item.description')
    %th= t('menu_item.type')
    %th= t('menu_item.price')
    %th
    %th
    %th

  - @menu_items.each do |menu_item|
    %tr
      %td= menu_item.name
      %td= menu_item.description
      %td= type_name(menu_item.item_type)
      %td= menu_item.price
      %td= link_to t(:show), menu_item
      %td= link_to t(:edit), edit_menu_item_path(menu_item)
      %td= link_to t(:destroy), menu_item, confirm: 'Are you sure?', method: :delete

%br/

= link_to t('New Menu item'), new_menu_item_path, class: "btn btn-large btn-success"

app/views/menu_items/new.html.haml
%h1 New menu_item

.row
	%div{class: "span6 offset3" }
		= render 'form'
		= link_to 'Back', menu_items_path, class: 'btn btn-inverse'

app/views/menu_items/show.html.haml
%p
  %b= "#{t('menu_item.name')} :"
  = @menu_item.name

%p
  %b= "#{t('menu_item.description')} :"
  = @menu_item.description

%p
  %b= "#{t('menu_item.type')}:"
  = type_name(@menu_item.item_type)

%p
  %b= "#{t('menu_item.price')} :"
  = @menu_item.price


= link_to t(:edit), edit_menu_item_path(@menu_item) 
|
= link_to t(:back), menu_items_path

app/views/shared/_error_messages.html.haml
- if object.errors.any?
	#error_explanation
		%div{:class => "alert alert-error"}
			The form contains = pluralize(object.errors.count, "error")
		%ul
			- object.errors.full_messages.each do |msg|
				%li= msg

app/views/static_pages/about.html.haml
= provide(:title, t('about_us'))
%h1= t('about_us')
%p
  The 
  %a{:href => '#'} eMenu
  is a project to make a restaurant's menu accesible from internet
  build with 
  %a{:href => 'http://rubyonrails.org/'} Ruby on Rails.

app/views/static_pages/contact.html.haml
= provide(:title, t('contact'))
%h1= t('contact')
%p
  Contact PerrIT about the eMenu app at the
  %a{href: "#"} contact page.

app/views/static_pages/help.html.haml
= provide(:title, t('help'))
%h1= t('help')
%p
  Get help on eMenu at the
  %a{ href: "#"} eMenu 
  help page.

app/views/static_pages/home.html.haml
%div{class: "center hero-unit"}
	%h1 Welcome to the eMenu

	%h2
		This is the home page for the
		%a eMenu 
		application.

	= link_to t("sign_up_now"), new_user_registration_path, class: "btn btn-large btn-success"

= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/'

app/views/users/show.html.haml
= provide(:title, current_user.name)

.row
	%aside.span2
		%section
			= image_tag current_user.image_url(:profile).to_s, class: 'avatar'
			%h1
				= current_user.name.to_s
	.span8
		%h3= t('menus')